#!/usr/bin/env python3
"""
Core 025 — Rescue Rule Miner (Top3→Top1) + Member Pocket Finder
Version: v1.0 (self-contained, no app edits)
Author: generated by ChatGPT for Iknw Walker

What it does (using ONLY your real exported lab CSVs):
- Loads one or more core025 per-event exports
- Normalizes/derives seed features directly from 4-digit seeds
- Computes baseline Top1 / Top1+Top2 member accuracy on hit-events
- Mines high-precision "Top3 was true" situations and proposes Top3→Top1 rescue rules
- Builds a separate view for seed_has_9 vs seed_no_9 regimes
- Exports rule tables to self-identifying filenames in the current folder

Run:
  python core025_rescue_rule_miner_v1.py --event core025_tier_per_event_run_train_to__bins21_cap80_runf947fdfc.csv

Or run in a folder containing your exports:
  python core025_rescue_rule_miner_v1.py --auto

Notes:
- This script does NOT simulate any draws. It only evaluates deterministic rule flips on your historical exported results.
- It does not modify your Streamlit app.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import glob
import math
import os
import re
from dataclasses import dataclass
from itertools import combinations
from typing import Dict, List, Optional, Tuple

import pandas as pd
import numpy as np


# ----------------------------
# Helpers: robust column finding
# ----------------------------

def _norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", str(s).lower())

def find_col(df: pd.DataFrame, candidates: List[str], required: bool = True) -> Optional[str]:
    cols = list(df.columns)
    norm_map = {_norm(c): c for c in cols}
    for cand in candidates:
        key = _norm(cand)
        if key in norm_map:
            return norm_map[key]
    # fuzzy contains
    for cand in candidates:
        key = _norm(cand)
        for n, c in norm_map.items():
            if key and key in n:
                return c
    if required:
        raise KeyError(f"Required column not found. Tried: {candidates}. Available columns: {cols[:60]}{'...' if len(cols)>60 else ''}")
    return None

def coerce_member(x) -> Optional[int]:
    """Coerce a member value to int in {25, 225, 255} if possible.

    Accepts inputs like: 25, "25", "0025", "0225", "0255", 225, "225", 255, "255".
    """
    if pd.isna(x):
        return None

    s = str(x).strip()
    parts = re.findall(r"\d+", s)
    if not parts:
        return None

    raw = parts[-1]        # last numeric group
    raw4 = raw.zfill(4)    # normalize for 4-digit member strings

    if raw4 in ("0025", "0225", "0255"):
        return int(raw4)   # int("0025") -> 25

    try:
        v = int(raw)
    except Exception:
        return None

    if v in (25, 225, 255):
        return v

    return None


def coerce_seed4(x) -> Optional[str]:
    if pd.isna(x):
        return None
    s = str(x).strip()
    m = re.findall(r"\d{4}", s)
    if m:
        return m[-1]
    # sometimes seed stored as 123 -> "0123"
    m2 = re.findall(r"\d+", s)
    if not m2:
        return None
    v = m2[-1]
    if len(v) <= 4:
        return v.zfill(4)
    return v[-4:]


# ----------------------------
# Feature derivation from seed
# ----------------------------

PAIR_MIRROR = {"0":"5","1":"6","2":"7","3":"8","4":"9","5":"0","6":"1","7":"2","8":"3","9":"4"}

def seed_digits(seed4: str) -> List[int]:
    return [int(ch) for ch in seed4]

def derive_seed_features(df: pd.DataFrame, seed_col: str) -> pd.DataFrame:
    s = df[seed_col].map(coerce_seed4)
    df = df.copy()
    df["seed4"] = s
    d = df["seed4"].dropna().map(seed_digits)
    # preallocate
    df["seed_sum_calc"] = np.nan
    df["seed_spread_calc"] = np.nan
    df["seed_absdiff_calc"] = np.nan
    df["seed_sum_lastdigit_calc"] = np.nan
    df["seed_has_9_calc"] = np.nan
    df["seed_even_ct_calc"] = np.nan
    df["seed_ct025_calc"] = np.nan
    df["seed_adj_absdiff_sum_calc"] = np.nan
    df["seed_pairwise_absdiff_sum_calc"] = np.nan

    # compute vectorized-ish
    idx = d.index
    arr = np.array(d.tolist(), dtype=int)
    df.loc[idx, "seed_sum_calc"] = arr.sum(axis=1)
    df.loc[idx, "seed_spread_calc"] = arr.max(axis=1) - arr.min(axis=1)
    df.loc[idx, "seed_absdiff_calc"] = np.abs((arr[:,0] + arr[:,1]) - (arr[:,2] + arr[:,3]))
    df.loc[idx, "seed_sum_lastdigit_calc"] = (arr.sum(axis=1) % 10)
    df.loc[idx, "seed_has_9_calc"] = (arr == 9).any(axis=1).astype(int)
    df.loc[idx, "seed_even_ct_calc"] = (arr % 2 == 0).sum(axis=1)
    df.loc[idx, "seed_ct025_calc"] = np.isin(arr, [0,2,5]).sum(axis=1)
    df.loc[idx, "seed_adj_absdiff_sum_calc"] = (np.abs(arr[:,0]-arr[:,1]) + np.abs(arr[:,1]-arr[:,2]) + np.abs(arr[:,2]-arr[:,3]))
    # unordered pairwise absdiff sum
    pair_sums = []
    for row in arr:
        ps = 0
        for i,j in combinations(range(4), 2):
            ps += abs(int(row[i]) - int(row[j]))
        pair_sums.append(ps)
    df.loc[idx, "seed_pairwise_absdiff_sum_calc"] = pair_sums

    # digit presence flags
    for dig in range(10):
        df[f"seed_has_d{dig}"] = df["seed4"].fillna("").str.contains(str(dig)).astype(int)

    # unordered pair flags (00..99 but unordered unique)
    for a in range(10):
        for b in range(a, 10):
            name = f"seed_has_pair_{a}{b}"
            def _has_pair(seed: str, a=a, b=b):
                if not isinstance(seed, str) or len(seed) != 4:
                    return 0
                ct_a = seed.count(str(a))
                ct_b = seed.count(str(b))
                if a == b:
                    return 1 if ct_a >= 2 else 0
                return 1 if (ct_a >= 1 and ct_b >= 1) else 0
            df[name] = df["seed4"].map(_has_pair).astype(int)

    return df


# ----------------------------
# Rule representation
# ----------------------------

@dataclass(frozen=True)
class Predicate:
    col: str
    op: str
    val: float

    def apply(self, df: pd.DataFrame) -> pd.Series:
        if self.op == "==":
            return df[self.col] == self.val
        if self.op == "!=":
            return df[self.col] != self.val
        if self.op == ">=":
            return df[self.col] >= self.val
        if self.op == "<=":
            return df[self.col] <= self.val
        if self.op == ">":
            return df[self.col] > self.val
        if self.op == "<":
            return df[self.col] < self.val
        raise ValueError(self.op)

    def __str__(self) -> str:
        v = int(self.val) if float(self.val).is_integer() else self.val
        return f"{self.col} {self.op} {v}"

@dataclass(frozen=True)
class Rule:
    preds: Tuple[Predicate, ...]

    def apply(self, df: pd.DataFrame) -> pd.Series:
        m = pd.Series(True, index=df.index)
        for p in self.preds:
            m &= p.apply(df)
        return m

    def __str__(self) -> str:
        return " AND ".join(str(p) for p in self.preds)


# ----------------------------
# Mining logic
# ----------------------------

def baseline_metrics(df: pd.DataFrame, true_col: str, t1: str, t2: str, t3: str) -> Dict[str, float]:
    t = df[true_col]
    m1 = (t == df[t1]).mean()
    m12 = (t.isin(df[[t1,t2]].stack().groupby(level=0).apply(set))).mean()  # slow-ish
    # faster:
    m12 = ((t == df[t1]) | (t == df[t2])).mean()
    m123 = ((t == df[t1]) | (t == df[t2]) | (t == df[t3])).mean()
    return {"Top1": float(m1), "Top1or2": float(m12), "Top1or2or3": float(m123)}

def apply_rescue_flip(df: pd.DataFrame, mask: pd.Series, t1: str, t2: str, t3: str) -> pd.DataFrame:
    """Promote Top3 to Top1 for masked rows; shift old Top1 -> Top2 -> Top3 (stable)."""
    out = df.copy()
    out.loc[mask, [t1,t2,t3]] = out.loc[mask, [t3,t1,t2]].values
    return out

def make_candidate_predicates(df: pd.DataFrame, cols_numeric: List[str], cols_bool: List[str]) -> List[Predicate]:
    preds: List[Predicate] = []
    for c in cols_bool:
        if c not in df.columns: 
            continue
        # only if both 0/1 exist
        vals = set(df[c].dropna().unique().tolist())
        if vals.issuperset({0,1}) or vals == {0,1}:
            preds.append(Predicate(c, "==", 1))
            preds.append(Predicate(c, "==", 0))
        elif len(vals) == 1:
            continue
        else:
            # treat as categorical small ints
            for v in sorted(vals)[:6]:
                preds.append(Predicate(c, "==", float(v)))

    for c in cols_numeric:
        if c not in df.columns:
            continue
        ser = df[c].dropna()
        if ser.empty:
            continue
        uniq = sorted(ser.unique())
        # limit thresholds
        if len(uniq) > 30:
            qs = ser.quantile([0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]).unique()
            thrs = sorted(set(float(x) for x in qs))
        else:
            thrs = [float(x) for x in uniq]
        for t in thrs:
            preds.append(Predicate(c, ">=", t))
            preds.append(Predicate(c, "<=", t))
    return preds

def score_rule_for_top3(df: pd.DataFrame, rule: Rule, true_is_top3: pd.Series, min_support: int = 8) -> Optional[Dict]:
    m = rule.apply(df)
    support = int(m.sum())
    if support < min_support:
        return None
    prec = float((true_is_top3[m]).mean()) if support else 0.0
    rec = float((true_is_top3[m]).sum() / true_is_top3.sum()) if true_is_top3.sum() else 0.0
    return {"rule": str(rule), "support": support, "precision_top3": prec, "recall_top3": rec}

def compute_net_gain(df: pd.DataFrame, rule: Rule, true_col: str, t1: str, t2: str, t3: str) -> Dict:
    base = baseline_metrics(df, true_col, t1, t2, t3)
    flipped = apply_rescue_flip(df, rule.apply(df), t1, t2, t3)
    after = baseline_metrics(flipped, true_col, t1, t2, t3)
    return {
        "Top1_base": base["Top1"],
        "Top1_after": after["Top1"],
        "Top1_gain": after["Top1"] - base["Top1"],
        "Top1or2_base": base["Top1or2"],
        "Top1or2_after": after["Top1or2"],
        "Top1or2_gain": after["Top1or2"] - base["Top1or2"],
    }


def mine_top3_rescue_rules(
    df: pd.DataFrame,
    true_col: str,
    t1: str,
    t2: str,
    t3: str,
    feature_cols_numeric: List[str],
    feature_cols_bool: List[str],
    max_rules: int = 40,
    min_support: int = 8,
) -> pd.DataFrame:
    true_is_top3 = df[true_col] == df[t3]
    if true_is_top3.sum() == 0:
        return pd.DataFrame()
    preds = make_candidate_predicates(df, feature_cols_numeric, feature_cols_bool)

    # 1-predicate rules
    scored = []
    for p in preds:
        r = Rule((p,))
        s = score_rule_for_top3(df, r, true_is_top3, min_support=min_support)
        if s is None:
            continue
        g = compute_net_gain(df, r, true_col, t1, t2, t3)
        s.update(g)
        scored.append(s)

    # take top singles by Top1_gain then try pairs
    singles = pd.DataFrame(scored)
    if singles.empty:
        return singles
    singles = singles.sort_values(["Top1_gain","precision_top3","support"], ascending=[False, False, False]).head(25)

    # build pair rules from the best predicates used in top singles
    best_pred_strs = set()
    for rs in singles["rule"].tolist():
        best_pred_strs.add(rs)
    # map back to predicate objects (string compare)
    pred_by_str = {str(Predicate(c,"==",1)): Predicate(c,"==",1) for c in []}  # placeholder to satisfy linter
    # rebuild mapping from all preds:
    pred_by_str = {str(p): p for p in preds}

    top_pred_objs = []
    for rs in singles["rule"].tolist():
        if rs in pred_by_str:
            top_pred_objs.append(pred_by_str[rs])
    top_pred_objs = list(dict.fromkeys(top_pred_objs))  # unique preserve order

    pair_scored = []
    for p1, p2 in combinations(top_pred_objs, 2):
        r = Rule((p1,p2))
        s = score_rule_for_top3(df, r, true_is_top3, min_support=min_support)
        if s is None:
            continue
        g = compute_net_gain(df, r, true_col, t1, t2, t3)
        s.update(g)
        pair_scored.append(s)

    out = pd.concat([singles, pd.DataFrame(pair_scored)], ignore_index=True)
    out = out.sort_values(["Top1_gain","precision_top3","support"], ascending=[False, False, False]).head(max_rules)
    return out


def mine_member_pockets(
    df: pd.DataFrame,
    true_col: str,
    member: int,
    feature_cols_numeric: List[str],
    feature_cols_bool: List[str],
    max_rules: int = 30,
    min_support: int = 8,
) -> pd.DataFrame:
    y = df[true_col] == member
    preds = make_candidate_predicates(df, feature_cols_numeric, feature_cols_bool)
    rows = []
    for p in preds:
        r = Rule((p,))
        m = r.apply(df)
        support = int(m.sum())
        if support < min_support:
            continue
        prec = float((y[m]).mean())
        rec = float((y[m]).sum() / y.sum()) if y.sum() else 0.0
        rows.append({"rule": str(r), "support": support, "precision": prec, "recall": rec})
    out = pd.DataFrame(rows)
    if out.empty:
        return out
    out = out.sort_values(["precision","support","recall"], ascending=[False, False, False]).head(max_rules)
    return out


# ----------------------------
# Main
# ----------------------------

def load_events(event_paths: List[str]) -> pd.DataFrame:
    parts = []
    for p in event_paths:
        df = pd.read_csv(p)
        df["__source_file__"] = os.path.basename(p)
        parts.append(df)
    return pd.concat(parts, ignore_index=True)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--event", action="append", default=[], help="Path to per-event export CSV (can repeat).")
    ap.add_argument("--auto", action="store_true", help="Auto-load all core025_tier_per_event*.csv in the current folder.")
    ap.add_argument("--min_support", type=int, default=8)
    ap.add_argument("--max_rules", type=int, default=40)
    args = ap.parse_args()

    event_paths = list(args.event)
    if args.auto:
        event_paths.extend(sorted(glob.glob("core025_tier_per_event*.csv")))
    event_paths = [p for p in event_paths if os.path.exists(p)]

    if not event_paths:
        print("❌ No per-event CSVs found.\n"
              "Provide at least one with --event <file.csv> or put them in this folder and run --auto.\n"
              "Expected names include:\n"
              "  core025_tier_per_event_run_train_to__bins21_cap80_runf947fdfc.csv\n"
              "  core025_tier_per_event_run_train_to__rows2-76_cap50_rune9173474.csv")
        return 2

    df = load_events(event_paths)
    print(f"Loaded {len(df):,} rows from {len(event_paths)} per-event file(s).")

    # Identify key columns (robust guesses)
    seed_col = find_col(df, ["Seed", "seed", "seed4", "seed_4d", "StreamSeed", "stream_seed", "SeedStr"], required=True)
    true_col = find_col(df, ["TrueMember", "true_member", "WinningMember", "winner_member", "WinMember", "MemberTrue", "true"], required=True)
    top1_col = find_col(df, ["Top1Member", "top1_member", "Pick1Member", "Top1", "top1"], required=True)
    top2_col = find_col(df, ["Top2Member", "top2_member", "Pick2Member", "Top2", "top2"], required=True)
    top3_col = find_col(df, ["Top3Member", "top3_member", "Pick3Member", "Top3", "top3"], required=True)

    # Normalize
    out = df.copy()
    out["seed4"] = out[seed_col].map(coerce_seed4)
    out["true_member"] = out[true_col].map(coerce_member)
    out["top1_member"] = out[top1_col].map(coerce_member)
    out["top2_member"] = out[top2_col].map(coerce_member)
    out["top3_member"] = out[top3_col].map(coerce_member)

    # Drop rows we can't score
    before = len(out)
    out = out.dropna(subset=["seed4", "true_member", "top1_member", "top2_member", "top3_member"]).copy()
    print(f"Scorable rows: {len(out):,} (dropped {before-len(out):,} with missing seed/member picks).")

    # Derive features from seed (no app edits)
    out = derive_seed_features(out, "seed4")

    # Choose feature columns for mining
    num_cols = [
        "seed_sum_calc", "seed_spread_calc", "seed_absdiff_calc", "seed_sum_lastdigit_calc",
        "seed_even_ct_calc", "seed_ct025_calc", "seed_adj_absdiff_sum_calc", "seed_pairwise_absdiff_sum_calc",
    ]
    bool_cols = ["seed_has_9_calc"] + [c for c in out.columns if c.startswith("seed_has_d")] + [c for c in out.columns if c.startswith("seed_has_pair_")]

    # Baseline metrics overall / regimes
    def summarize(sub: pd.DataFrame, label: str):
        b = baseline_metrics(sub, "true_member", "top1_member", "top2_member", "top3_member")
        top3_true = int((sub["true_member"] == sub["top3_member"]).sum())
        top3_by_member = sub.loc[sub["true_member"] == sub["top3_member"], "true_member"].value_counts().to_dict()
        print(f"\n=== {label} ===")
        print(f"Events: {len(sub):,}")
        print(f"Top1: {b['Top1']*100:.1f}% | Top1+Top2: {b['Top1or2']*100:.1f}% | Top1+Top2+Top3: {b['Top1or2or3']*100:.1f}%")
        print(f"Top3-was-true: {top3_true:,} ({(top3_true/len(sub))*100:.1f}%) | breakdown: {top3_by_member}")

    summarize(out, "ALL seed regimes")
    summarize(out[out["seed_has_9_calc"]==1], "seed_has_9")
    summarize(out[out["seed_has_9_calc"]==0], "seed_no_9")

    # Mine rescue rules
    print("\nMining Top3→Top1 rescue rules (overall)...")
    rules_all = mine_top3_rescue_rules(out, "true_member", "top1_member", "top2_member", "top3_member", num_cols, bool_cols, max_rules=args.max_rules, min_support=args.min_support)
    print(f"Found {len(rules_all):,} candidate rescue rules (ALL).")

    print("\nMining Top3→Top1 rescue rules (seed_has_9)...")
    rules_9 = mine_top3_rescue_rules(out[out["seed_has_9_calc"]==1], "true_member", "top1_member", "top2_member", "top3_member", num_cols, bool_cols, max_rules=args.max_rules, min_support=max(4, args.min_support//2))
    print(f"Found {len(rules_9):,} candidate rescue rules (seed_has_9).")

    print("\nMining Top3→Top1 rescue rules (seed_no_9)...")
    rules_no9 = mine_top3_rescue_rules(out[out["seed_has_9_calc"]==0], "true_member", "top1_member", "top2_member", "top3_member", num_cols, bool_cols, max_rules=args.max_rules, min_support=args.min_support)
    print(f"Found {len(rules_no9):,} candidate rescue rules (seed_no_9).")

    # Member pockets
    pockets = {}
    for member in (25, 225, 255):
        pockets[member] = mine_member_pockets(out, "true_member", member, num_cols, bool_cols, max_rules=20, min_support=args.min_support)

    # Export
    ts = _dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    def save(df_: pd.DataFrame, stem: str):
        if df_ is None or df_.empty:
            return None
        fn = f"core025_{stem}__{ts}.csv"
        df_.to_csv(fn, index=False)
        return fn

    fn_all = save(rules_all, "rescue_rules_ALL")
    fn_9 = save(rules_9, "rescue_rules_seed_has_9")
    fn_no9 = save(rules_no9, "rescue_rules_seed_no9")

    pocket_files = []
    for m, pdf in pockets.items():
        f = save(pdf, f"member_pockets_{m}")
        if f: pocket_files.append(f)

    # Display top rules to console
    def show(df_: pd.DataFrame, title: str, n: int = 15):
        if df_ is None or df_.empty:
            print(f"\n{title}: (none)")
            return
        cols = ["rule","support","precision_top3","recall_top3","Top1_gain","Top1_base","Top1_after"]
        keep = [c for c in cols if c in df_.columns]
        print(f"\n{title} (top {min(n,len(df_))})")
        print(df_[keep].head(n).to_string(index=False))

    show(rules_all, "TOP Rescue rules — ALL")
    show(rules_9, "TOP Rescue rules — seed_has_9")
    show(rules_no9, "TOP Rescue rules — seed_no_9")

    for member in (25,225,255):
        pdf = pockets[member]
        if pdf is None or pdf.empty:
            continue
        print(f"\nMember pockets — {member} (top 10)")
        print(pdf.head(10).to_string(index=False))

    print("\nExports:")
    for fn in [fn_all, fn_9, fn_no9, *pocket_files]:
        if fn:
            print(f" - {fn}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
